### 변수를 overwrite 하는 방법? 다른 파일의 변수를 이용하는 방법?
### 결국 swagger 인가
### @accessToken = {{login.response.body.accessToken}}
### @refreshToken = {{login.response.body.refreshToken}}
### 변수 셋팅은 되나 overwrite 가 안됨....

@baseUrl = http://localhost:3000
@authEmail = zzingo3@gmail.com
@authPassword = 123123
@authNickname = zzingo3

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inp6aW5nbzNAZ21haWwuY29tIiwic3ViIjo0LCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzA2NTc2MTAyLCJleHAiOjE3MDY1NzY0MDJ9.fZYxQbhWAAsCdLOCx1kGETlLDU2dhs9QuJR8RLEAZOY
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inp6aW5nb0BnbWFpbC5jb20iLCJzdWIiOjEsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzA1OTY2NTcyLCJleHAiOjE3MDU5NzAxNzJ9.qRss9xIrd0pO4VGxgh9g5jaeiAsdpp2g2y4DzgkIUEc

#########################
### Auth
#########################

# @name login
POST {{baseUrl}}/auth/login/email
Authorization: Basic {{authEmail}}:{{authPassword}}

###

# @name register
POST {{baseUrl}}/auth/register/email
content-type: application/json

{
  "email": "{{authEmail}}",
  "password": "{{authPassword}}",
  "nickname": "{{authNickname}}"
}

###

# @name rotateAccess
POST {{baseUrl}}/auth/token/access
Authorization: Bearer {{refreshToken}}

###

# @name rotateRefresh
POST {{baseUrl}}/auth/token/refresh
Authorization: Bearer {{refreshToken}}


#########################
### Posts
#########################

GET {{baseUrl}}/posts
###

GET {{baseUrl}}/posts?order__createdAt=DESC

###

GET {{baseUrl}}/posts?order__createdAt=DESC&page=1&where__likeCount__more_than=49

###

GET {{baseUrl}}/posts?order__createdAt=DESC&take=1

###

GET {{baseUrl}}/posts?order__createdAt=DESC&page=1&where__likeCount__more_than=49&where__title__i_like=2

###

POST {{baseUrl}}/posts/random
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/posts/1

###

GET {{baseUrl}}/posts/4

###

POST {{baseUrl}}/posts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{  
  "title": "포스트 1",
  "content": "포스트 1 내용",
  "images": [    
  ]
}

###

PATCH  {{baseUrl}}/posts/108
Authorization: Bearer {{accessToken}}
content-type: application/json

{
  "title": "hori love3"
}

###

DELETE {{baseUrl}}/posts/99
Authorization: Bearer {{accessToken}}

#########################
### Users
#########################

GET {{baseUrl}}/users

###

POST {{baseUrl}}/users
content-type: application/json

{
  "nickname": "hori",
  "email": "hori@hori.com",
  "password": "123123"
}

#########################
### Common
#########################

POST {{baseUrl}}/common/image
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="testimage.jpg"
Content-Type: image/jpeg

< ./testimage.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

#########################
### Comments
#########################

GET {{baseUrl}}/posts/107/comments

###

GET {{baseUrl}}/posts/107/comments/1

###

POST {{baseUrl}}/posts/107/comments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{  
  "comment": "강의 너무 좋아요!!"
}

###

PATCH {{baseUrl}}/posts/107/comments/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{  
  "comment": "Nest JS 너무 재밌어요!!"
}

