### 변수를 overwrite 하는 방법? 다른 파일의 변수를 이용하는 방법?
### 결국 swagger 인가
### @accessToken = {{login.response.body.accessToken}}
### @refreshToken = {{login.response.body.refreshToken}}
### 변수 셋팅은 되나 overwrite 가 안됨....

@baseUrl = http://localhost:3000
@authEmail = zzingo@gmail.com
@authPassword = 123123
@authNickname = zzingo

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inp6aW5nb0BnbWFpbC5jb20iLCJzdWIiOjEsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3MDYwMDMzNjgsImV4cCI6MTcwNjAwMzY2OH0.lbfeL5b9o84BJe1mLMvW7hqYXjkPyYjN6G3_sKmjvbU
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inp6aW5nb0BnbWFpbC5jb20iLCJzdWIiOjEsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzA1OTY2NTcyLCJleHAiOjE3MDU5NzAxNzJ9.qRss9xIrd0pO4VGxgh9g5jaeiAsdpp2g2y4DzgkIUEc

#########################
### Auth
#########################

# @name login
POST {{baseUrl}}/auth/login/email
Authorization: Basic {{authEmail}}:{{authPassword}}

###

# @name register
POST {{baseUrl}}/auth/register/email
content-type: application/json

{
  "email": "{{authEmail}}",
  "password": "{{authPassword}}",
  "nickname": "{{authNickname}}"
}

###

# @name rotateAccess
POST {{baseUrl}}/auth/token/access
Authorization: Bearer {{refreshToken}}

###

# @name rotateRefresh
POST {{baseUrl}}/auth/token/refresh
Authorization: Bearer {{refreshToken}}


#########################
### Posts
#########################

GET {{baseUrl}}/posts
###

GET {{baseUrl}}/posts?order__createdAt=ASC

###

GET {{baseUrl}}/posts?order__createdAt=DESC&page=1&where__likeCount__more_than=49

###

GET {{baseUrl}}/posts?order__createdAt=DESC&page=1&where__likeCount__more_than=49&where__title__i_like=2

###

POST {{baseUrl}}/posts/random
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/posts/1

###

GET {{baseUrl}}/posts/4

###

POST {{baseUrl}}/posts
Authorization: Bearer {{accessToken}}
content-type: application/json

{  
  "title": "포스트7",
  "content": "포스트7 post 테스트"
}

###

PATCH  {{baseUrl}}/posts/2
content-type: application/json

{
  "title": "hori love"
}

###

DELETE {{baseUrl}}/posts/1

#########################
### Users
#########################

GET {{baseUrl}}/users

###

POST {{baseUrl}}/users
content-type: application/json

{
  "nickname": "hori",
  "email": "hori@hori.com",
  "password": "123123"
}

###