GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/1

###

GET http://localhost:3000/posts/4

###

POST http://localhost:3000/posts
content-type: application/json

{
    "author": "codefactory",
    "title": "포스트4",
    "content": "포스트 post 테스트"
}

###

PUT http://localhost:3000/posts/3
content-type: application/json

{
    "author": "hori"
}

###

DELETE http://localhost:3000/posts/3