POST http://localhost:3000/auth/login/email
Authorization: Basic enppbmdvQGdtYWlsLmNvbToxMjMxMjM=

###

POST http://localhost:3000/auth/register/email
content-type: application/json

{
  "email": "zzingo@gmail.com",
  "password": "123123",
  "nickname": "zzingo"
}

###

POST http://localhost:3000/auth/token/access
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inp6aW5nb0BnbWFpbC5jb20iLCJzdWIiOjEsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzA1ODk3NTczLCJleHAiOjE3MDU5MDExNzN9.RZ4v49SQX63zkt4zEvAL604N9F2AQnpH9PXnxxrFGPA

###

POST http://localhost:3000/auth/token/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inp6aW5nb0BnbWFpbC5jb20iLCJzdWIiOjEsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzA1ODk3NTczLCJleHAiOjE3MDU5MDExNzN9.RZ4v49SQX63zkt4zEvAL604N9F2AQnpH9PXnxxrFGPA